### ISSUE TITLE
Clear output screen on restart blockly EV3 program.

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#10]
When creating a blockly EV3 program that writes a line, running it multiple times overwrites the output screen so it becomes quite messy.

Suggest clearing output screen 

<img width="695" alt="screen shot 2016-01-18 at 12 28 07 am" src="https://cloud.githubusercontent.com/assets/16690260/12381079/5dc61282-bd7a-11e5-8922-bc1b2803c39c.png">

**Comment by MarkusBordihn** [comment]
Currently clearing the output is not supported by jquery-turtle so this is something which needs to be implemented in jquery-turtle itself.
