### ISSUE TITLE
Unable to open plain text

### ISSUE THREAD

**Issue by Jimsy2** [google/coding-with-chrome#100]
Raw text files with file extension `.txt` can not be opened in CwC.
The window title changes to the file name of the opend file but the window remains empty.

I am using Chrome Version 55.0.2883.105 (64-bit)
on Chrome OS Plattform 8872.76.0 (Official Build) stable-channel edgar

**Comment by MarkusBordihn** [comment]
Thanks for the report.

Note: The file data are loaded as "raw" but interpreted as "custom" which results in an empty screen.
