### ISSUE TITLE
Color modes (colorblind/night mode)

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#106]
How are colors assigned in CWC, and more importantly: would it be easy to select certain default color sets for various situations?

- Accessibility: colorblind people might have issues with CWC
- Night Mode: (less important IMO, but hey, if we're playing with colors anyway...): working at night with high contrast.

**Comment by MarkusBordihn** [comment]
Unfortunately we are restricted by other external packages for this.
I really like the idea, but Blockly or Material Design light is currently not supporting something like this.

Please follow up with these team to see if there are any plans for this.
