### ISSUE TITLE
Grid Overlay

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#107]
To do mathematics with Coding with Chrome it would be useful to have a button that shows a grid overlay with pixel counts (coordinates).

**Comment by MarkusBordihn** [comment]
Any idea how the icon should look like ?
See https://material.io/icons/

**Comment by MartenvanWezel** [comment]
How about https://material.io/icons/#ic_border_clear - border_clear ?

**Comment by mfurkan60** [comment]
How about  , can we use this site? https://icons8.com/icons/set/grid 
like this icon >>
![icons8-save-to-grid-80](https://user-images.githubusercontent.com/47870290/80022372-a42c5480-84e4-11ea-91a3-f58e848d1b5e.png)
