### ISSUE TITLE
Instant Tooltips

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#114]
(after UX review)

Tooltips in CWC are quite flaky. Sometimes they show up, sometimes it takes a certain time, sometimes they don't.

Can this be made consistent? My current best guess about the best implementation is:

(when hovering over an icon):
1/ Nothing for 0.5 seconds
2/ Show tooltip

Then:
When clicking or moving off the same surface (e.g. to another window, or to another section of the UI), reset. And wait 0.5s again

When showing a tooltip and then moving from one tool to the next one, immediately show next tooltip. 

If that's too much work, a simple solution would be fine (e.g. always instant tooltip) or 'always after 0.4 secs'.

**Comment by MarkusBordihn** [comment]
Could you please provide some more specific examples.
Most of the tool-tips on the UI, are using material design light, so we are not really able to adjust the behavior.
