### ISSUE TITLE
Play/pause/stop autorun

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#115]
It seems to me that the controls to play/pause code is very cluttered and can be simplified a lot:

One button: Play. If pressed, turn into "stop" (so if you click again it would stop running)
If in 'play' mode, then indeed autorun after each codechange et.

I don't really see the benefit of all the play, stop etc etc buttons, too complex for a simple IDE. We could hide the 'force stop' or something button deeper in a menu?

**Comment by MarkusBordihn** [comment]
There are some edge case when the "preview" crashes or is loading ongoing data where this one button solution would never show an stop button because the windows has never finished loading, but still execute the code.
