### ISSUE TITLE
Search for Images in File Library broken

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#117]
File Library button -> Search Tab
Type a search and hit search button

-> opens a browser. Unclear what to do next. (dragging an image to the CWC window doesn't work)

Something else intended, I assume?

**Comment by MartenvanWezel** [comment]
This actually doesn't work yet - using image search still opens a browser rather than importing images. If there are extra instructions (for example "drag images from image search into CwC.. ) then we need to add them at least?

**Comment by MarkusBordihn** [comment]
Fixed in the latest dev build.
