### ISSUE TITLE
File library broken

### ISSUE THREAD

**Issue by Jimsy2** [google/coding-with-chrome#118]
On Chrome OS Version 59.0.3071.113

Images uploaded to the file library for HTML5 Markup project  are lost after restart of the CwC app.
The file library tutorial is shown on every relaunch of the CwC app.
`Insert image...` does not insert images in HTML5 Markup project.

**Comment by MarkusBordihn** [comment]
Should be fixed by a9a414751f4e8b3cef2a9b6017b6e7c7473e1cd5.

Basically you can't have an file library for an raw .html file, but I added something to embed images as base64 data url encoded urls.
