### ISSUE TITLE
Implementing Accessibility Features (1. Keyboard navigation)

### ISSUE THREAD

**Issue by Remixt** [google/coding-with-chrome#121]
I'm attempting to implement keyboard navigation within the application. My intent is to allow selecting codeblocks and putting them in the workspace through the use of navigation keys (arrow, enter, ect...)

Are there any suggestions on how to best accomplish this? I've looked at the accssible version of blockly, but it seems to replace the user interface with a much less refined version, and I haven't been able to figure how to inject it into coding with chrome yet.

The documentation suggests that I create an issue here.

**Comment by Outofit08** [comment]
Has there been any update to this? I would like to add keyboard navigation into the workspace area like wasd on the block selection.
