### ISSUE TITLE
Consider Adding Lego WeDo

### ISSUE THREAD

**Issue by kgasser13** [google/coding-with-chrome#126]
To the Robots area, can Lego WeDo consider being added to work with Chromebooks for students?

**Comment by kgasser13** [comment]
@MarkusBordihn Thank you for addressing this!

**Comment by MarkusBordihn** [comment]
We solved most of the Bluetooth LE issues and will start integrating BLE devices like the Lego WeDo very soon.

**Comment by MartenvanWezel** [comment]
Wedo2 is now supported in experimental mode, no?
