### ISSUE TITLE
Quotation Marks Regression - From Chrome Store comment

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#127]
Quotation marks not working in Python
The quotation marks are suddenly not working for my students when using Python. It was working earlier, and now it is not.
Thanks!
Posted by Kristina Johnson - Nov 28, 2017

**Comment by MarkusBordihn** [comment]
Please provide an exact example and the steps to reproduce the issue.
I assume that they try to use Python 2.7 code in Python 3.x or the other way around.
