### ISSUE TITLE
WASD support - From Chrome Store Comments

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#128]
WASD controls
Hi, I'v been hitting a problem that has been keeping me from doing alot of things. Basically I cant get the "S" key to work in the program. W,A, and D all work fine, but S doesn't

**Comment by MarkusBordihn** [comment]
Please provide an example for this, the game engine is using WASD keys for controls which worked fine.

**Comment by rowbottomn** [comment]
Could you clarify which mode this is happening?
