### ISSUE TITLE
Blockly programs always detected as 'changed, do you want to continue?' even if they are not

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#13]
E.g. load a blockly example from gallery, then try to go back to main screen. It will say changes are not saved, even if I didn't change anything.

**Comment by MarkusBordihn** [comment]
Technical for the editor it is an change, because its was empty before and then you load an example.

**Comment by MartenvanWezel** [comment]
It  does the same though if you load a file off disk. Most text editors/IDEs do not consider that a changed file.

**Comment by MarkusBordihn** [comment]
Good point, will change the detection to ignore loaded files.

**Comment by MarkusBordihn** [comment]
Please retest the newest version ...
