### ISSUE TITLE
Lack of feedback on use of Audio

### ISSUE THREAD

**Issue by rowbottomn** [google/coding-with-chrome#131]
When using the audio in blockly.  I can audio working perfectly fine.  However, many times the inclusion of audio causes the preview to hang indefinitely with no feedback to the programmer.  We have had to blindly try to avoid the probably causes but the lack of feedback is the issue.  We get it working for sure if the file is ?smaller than ~250 kb? and ?the files has no spaces? and the ?file is a mp3 over a wav format?.  I have included questions marks because I have not tested properly the bounds of these conditions.  

Again, the issues could be supported by including error messaging like "Files over 250kb are not supported"....

Just want to reaffirm my love for this project.

**Comment by MartenvanWezel** [comment]
Hi Nathan,

Do you have some sample CWC files we can take a look at? Frankly I'm not completely sure how you even managed to include and address audio files ;)
