### ISSUE TITLE
Translation to Hindi

### ISSUE THREAD

**Issue by SetCodesToFire** [google/coding-with-chrome#133]
Hello I would like to make a Hindi translation to make coding-with-chrome more accessible.

Can i contribute in this project? I have signed the CLA. My understanding with a previous issue #88 shows me that i need to create a local/[language-initials]/translation.js

What name should I pick for Hindi?

**Comment by MartenvanWezel** [comment]
Yes!

Thank you SetCodesToFire, it is alway good to have someone who understands the code and language to do this. The international language code for hindi is "hi".

Please go ahead and create a pull request when you are ready. Indeed it is

locales/hi/translation.js

-M

**Comment by SetCodesToFire** [comment]
Welcome. I will create a PR after some time.

**Comment by MarkusBordihn** [comment]
Thanks a lot for offering your support on this, please create a new file with the name:
local/hin/translation.js for the Hindi translation.

You could use local/eng/translation.js as reference or just start translating the main parts.

I will update the [I18n instruction](https://github.com/google/coding-with-chrome/blob/master/doc/I18N.md) with the workflow for testing such changes.

**Comment by MartenvanWezel** [comment]
Thank you SetCodesToFire - we intend to push a new version containing your code in a few days.

**Comment by SetCodesToFire** [comment]
Welcome @MartenvanWezel ,

I want to know where to start looking for contributing into this project more. I see there are many commits so i scrolled way back to the very first commit of the project and found myself lost.

**Comment by MartenvanWezel** [comment]
Hi - please feel free to send me a mail at codingwithchrome@google.com  - we can discuss in detail.

(but of course you can just start taking issues, but maybe you feel like a bigger project, we have tons of ideas and not enough time ourselves =) )

Cheers,

-Marten

**Comment by SetCodesToFire** [comment]
I sent you a mail... Subject mentioned is

setCodesToFire to Marten van Wezel 

:)
