### ISSUE TITLE
Backspace key fail in website output

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#14]
Perhaps this is a Chrome quirk, but the example form javascript works, but if you try to edit the input name box (and use backspace to remove what you typed) it doesn't work.(and I'm worried what I deleted.. I heard a 'rrrip' sound... possibly a blockly block delete sound)

**Comment by MarkusBordihn** [comment]
Please provide an step by step instruction.

**Comment by MartenvanWezel** [comment]
1/ Load "Websites" example from gallery
2/ Input your name
3/ Add a letter to your name
4/ Try to remove the letter

**Comment by MarkusBordihn** [comment]
Works for me. :8ball:

**Comment by MartenvanWezel** [comment]
Strange... Let me try to narrow it down
