### ISSUE TITLE
Saving not working 100% correctly

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#15]
- Hitting 'Save' shows the save dialog with the entire filename selected. If you then start to type, the extension (.cwc) is overwritten too. It is common to only select the actual name of the file, so the extension is preserved.

- If I save a file, the window title does not change to <filename>

- Might be good to put a (*) in front of the filename if changes are made

**Comment by MarkusBordihn** [comment]
Its an Chrome limitation that I could only suggest an full file name.
So its not possible to log an certain mime type.

But putting a (*) in front of the filename is a good idea.
