### ISSUE TITLE
Two issues in the app's setting when QA/testing CWC

### ISSUE THREAD

**Issue by tonyhua85** [google/coding-with-chrome#157]
In app's setting I encountered two issues:

1) After disabling some modules e.x. java module and coffee module, they will not show in the "overview" section but are still accessible in their subsection.

2) While in setting, clicking on "new project" or "new file" at the left side will not work.  I have to click "close settings" button to go back to the main screen.  

Please advise, Thanks

**Comment by MartenvanWezel** [comment]
Thanks Tony!

**Comment by MartenvanWezel** [comment]
(And Markus for fixing ;) )
