### ISSUE TITLE
Improved examples

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#16]
Sphero:
- It's a little 'meh' to have to wait for it to stop blinking, and also it takes a LONG time to finish 4 cycles. Improved IMO

Website:
- Slightly more elaborate version that clearly does some 'processing' with the form. (also typo: form, not formular)

[Examples.zip](https://github.com/google/coding-with-chrome/files/95057/Examples.zip)

**Comment by MarkusBordihn** [comment]
Next time please submit something like this as real CL.

**Comment by MartenvanWezel** [comment]
Yep sorry, I'm a perforce guy so I need to learn git and I wanted this to be done asap ;)
