### ISSUE TITLE
Demo Video

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#17]
URL as discussed, image attached. Text, perhaps "Quick Intro"

<img width="876" alt="cwcdemo" src="https://cloud.githubusercontent.com/assets/16690260/12428775/8cbc3930-bede-11e5-9db2-e8dae8e55982.png">

Also put all video links in 'Resources' as well..

**Comment by MartenvanWezel** [comment]
ps of course image should be scaled down to 'reasonable' :) don't need to dominate the main screen, but perhaps 1/5 of full screen size.

**Comment by MarkusBordihn** [comment]
@MartenvanWezel 
Could you please provide the URLs, because I have left my laptop at work. ^^°

**Comment by MartenvanWezel** [comment]
https://www.youtube.com/watch?v=Cbpug5Atmmo
https://www.youtube.com/watch?v=S3DhDiw0pXs
https://www.youtube.com/watch?v=R4XE3GW1EUc
https://www.youtube.com/watch?v=CkoJWKWIWFU

**Comment by MartenvanWezel** [comment]
Hey Markus, can you also put the #1 video in the main CWC screen, with as 'icon' the image attached to this issue?

quick mockup:
<img width="1279" alt="mock" src="https://cloud.githubusercontent.com/assets/16690260/12435120/4750a1ae-bf03-11e5-8eaa-564d22d2a3e4.png">

**Comment by MarkusBordihn** [comment]
I don't see any video which looked like the 'icon' so if you could provide me the video I could implement it.

I don't want to use one of the former videos because they very good but more for advanced users, so we should show an simple example with Blocks as quick intro instead.

**Comment by MartenvanWezel** [comment]
True, we currently don't have a better video. :) - but video #1 does show a 'demo' of how to use CwC so I figured we would use that video until we build a better one. I hope Timothy will make one, else maybe I will

**Comment by MartenvanWezel** [comment]
(I just pieced together the icon to show CwC in one of its most powerful modes, not intended to be a representation of the actual video just yet)
