### ISSUE TITLE
Tspan in SVG is not the position  Please check it in browser

### ISSUE THREAD

**Issue by Aspire0423** [google/coding-with-chrome#175]
![1529657471 1](https://user-images.githubusercontent.com/37784957/41767876-5e132a76-763d-11e8-81f1-e2d976d15bda.png)

**Comment by MarkusBordihn** [comment]
I assume you want to file an Chrome render bug and not an issue specific to the "Coding with Chrome" app.
If yes, please use https://bugs.chromium.org/p/chromium/issues/list instead.
