### ISSUE TITLE
Booting, stuck on 'loading cache' when running from npm

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#183]
Note: this happens when running 'npm run launch' - installing the built chrome app works.
<img width="978" alt="screen shot 2018-08-29 at 11 35 56 pm" src="https://user-images.githubusercontent.com/16690260/44819513-008e8200-abe5-11e8-8ec8-16bd90d01a61.png">

**Comment by MarkusBordihn** [comment]
Please provide a full step by step instruction to reproduce the issue. Thanks.
