### ISSUE TITLE
Joydemo disabled warning should be moved

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#224]
<img width="1076" alt="screen shot 2019-02-12 at 16 00 10" src="https://user-images.githubusercontent.com/16690260/52648988-59c24780-2edf-11e9-8783-e70be79a59a1.png">

Since this applies to all vision kit, I would either copy the warning to all tiles, or put it under the 'vision kit' header.

**Comment by zufishanali** [comment]
Hi, I am a fairly new contributor. May I work on this issue? 

Regards, 
Zufishan

**Comment by MartenvanWezel** [comment]
Hi Zufishan, 

Yes please, we are very happy to have you contribute! Please let us know if you need any help. 

-M
