### ISSUE TITLE
install fails on Snow Leopard OSX

### ISSUE THREAD

**Issue by raul1991** [google/coding-with-chrome#23]
The npm install command fails with this log...

> npm ERR! install Couldn't read dependencies
> npm ERR! Darwin 14.5.0
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v4.2.4
> npm ERR! npm  v2.14.12
> npm ERR! path /Users/rahulbawa/package.json
> npm ERR! code ENOPACKAGEJSON
> npm ERR! errno -2
> npm ERR! syscall open
> 
> npm ERR! package.json ENOENT: no such file or directory, open '/Users/rahulbawa/package.json'
> npm ERR! package.json This is most likely not a problem with npm itself.
> npm ERR! package.json npm can't find a package.json file in your current directory.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /Users/rahulbawa/npm-debug.log
>

**Comment by MarkusBordihn** [comment]
Please make sure to execute the command inside the "coding-with-chrome" folder.
According your log you execute the command directly under your user directory and not inside the extracted / pulled "coding-with-chrome" folder.
