### ISSUE TITLE
Basic obviously not implemented correctly.

### ISSUE THREAD

**Issue by kluzzebass** [google/coding-with-chrome#27]
I tried to do some Basic coding, but when I wrote the following program, I got a weird error that I couldn't cut & paste:

10 print "Hello, World!"
20 goto 10

@MartenvanWezel told me to file a bug report.

**Comment by MartenvanWezel** [comment]
Sounds like a fun easter egg to implement some "Nice try, clever clogs" popup if the first line of the written code contains "10 print "
