### ISSUE TITLE
Do we still need "Windows-Build-Tools" to be explicitly installed to run this project?.

### ISSUE THREAD

**Issue by SampathKumar27896** [google/coding-with-chrome#277]
From the BUILD.md file I can see we need to install windows-build-tools for the the windows users.
I found the description from the repository **Windows-Build-Tools**  which states that 
_Please note that the official [Node.js for Windows installer](https://nodejs.org/en/download/) can now automatically install the required tools. That's likely a much better option than the module listed here (windows-build-tools)._.

**Comment by MarkusBordihn** [comment]
Thanks for the note, I will remove this text.
