### ISSUE TITLE
Better Sphero implementation

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#28]
Whatever Sphero Sensors are available, implement in blockly and javascript. Ideally multiple blocks including a binary "triggered or not" and perhaps a full "value"

**Comment by MarkusBordihn** [comment]
* Sensor support (colision, speed, accelation)
* Control over keyboard
* Better calibration screen
* Pathfinder over x:y
* more examples ...

**Comment by MarkusBordihn** [comment]
Next steps are finalized in e6e46ba57d474c67cbff3ea72db6f90b6b27a6d0
