### ISSUE TITLE
Main Screen resizing is strange

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#32]
When making the main (welcome) screen smaller, some empty space is kept on the right side, so the menu items are sliding down unnecessarily.
<img width="428" alt="screen shot 2016-03-24 at 1 31 05 am" src="https://cloud.githubusercontent.com/assets/16690260/14005942/1ac130d8-f160-11e5-9651-76ec1759e439.png">

**Comment by MarkusBordihn** [comment]
Should be fixed in new welcome screen.
