### ISSUE TITLE
Sphero movement block - rotate the direction thing

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#5]
Currently "0 degrees" is pointing right. I would find it more intuitive if we make 0 degrees point up.

**Comment by MarkusBordihn** [comment]
"heading 0" should point forward, please make sure that you calibrate your Sphero accordingly.

**Comment by puntloos** [comment]
Yes, but the image in CwC (the circle with degrees selector) points right
(and it should point up) -

**Comment by MarkusBordihn** [comment]
No I got it. You mean the popup screen for setting the angel.

The mathematical standard is to have 0 degree on the right, but I agree that it would be more intuitive in this case to make 0 degrees point up.

**Comment by MarkusBordihn** [comment]
Open feature request at https://github.com/google/blockly/issues/239
