### ISSUE TITLE
Menu tiles should all be fully clickable

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#55]
Every menu tile in the select screen should be entirely clickable, not just the bottom 'launch..' link.

<img width="323" alt="screen shot 2016-04-24 at 3 51 10 pm" src="https://cloud.githubusercontent.com/assets/16690260/14768265/1efcd222-0a35-11e6-9fd7-7566c60dc887.png">

**Comment by MarkusBordihn** [comment]
Material design said "no".

e.g. https://getmdl.io/templates/portfolio/index.html

**Comment by MartenvanWezel** [comment]
OK but that sample site at least doesn't highlight the tile. 
Not sure if that matters or not. Let me ask Tim from UX
