### ISSUE TITLE
Advanced - Programming Language does not have a 'submenu' in the top bar

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#56]
If you go to Robots -> EV3 you see the top menu bar get a submenu 'EV3 Sphero'
If you go to Advanced - Programming you should see one too - (JavaScript | Coffeescript | PencilCode)

**Comment by MarkusBordihn** [comment]
You see it once you have selected one of the sub menus.
I removed it from the overview, because of the duplication of links.
