### ISSUE TITLE
Unable to rename variable or create new

### ISSUE THREAD

**Issue by mrpoponz** [google/coding-with-chrome#64]
Using blocky on version 3.5.16 in chrome on windows and an asus c201 chromebook.

**To replicate**
Beginner - Blocky -> Drag a variable -> Rename or new

**Behavior**
Nothing happens

**Expected behavior**
Input box on screen

**Notes**
I've also tried https://blockly-demo.appspot.com/static/demos/interpreter/index.html and it works fine so it may not be a browser problem.

**Comment by MarkusBordihn** [comment]
Blockly is using "window.prompt" for these actions which is blocked for Chrome Apps and Extensions by default.

**Comment by bdolicki** [comment]
Please prioritize this. It essentially prevents users from using variables (or rather, more than one variable called "item"). That makes a lot of programs impossible to write :)

**Comment by MarkusBordihn** [comment]
Reference:
https://github.com/google/blockly/issues/393

**Comment by MarkusBordihn** [comment]
@MartenvanWezel 
Please test and update the bundled version on the Chromestore to fix this issue.

**Comment by MartenvanWezel** [comment]
Nope. Build from scratch failed. (master branch)

[14%] cwc.ui.Builder Compiling 56 soy files to /var/folders/k8/b9b7qkln48j74xb5z[15%] cwc.ui.Builder Compiled 56 soy files to /var/folders/k8/b9b…sure-builder-N[16%] cwc.ui.Builder Compiling Closure Files (1.8 sec)[Closure Compiler Error] 1 errors for genfiles/js/cwc_ui.js:node_modules/blockly/blocks/lists.js:68: WARNING - missing require: 'Blockly.Mutator'
    this.setMutator(new Blockly.Mutator(['lists_create_with_item']));

**Comment by MartenvanWezel** [comment]
node_modules/blockly/core/field_variable.js:29: ERROR - required "Blockly.Events.Change" namespace never provided
goog.require('Blockly.Events.Change');
^

1 error(s), 68 warning(s)

**Comment by MarkusBordihn** [comment]
Travis CL said everything is fine now:
https://travis-ci.org/google/coding-with-chrome

Please make sure to run "npm run update" before, to fetch the latest changes.

**Comment by MarkusBordihn** [comment]
Fixed version if live now.

**Comment by mrpoponz** [comment]
Would this be the same for "window.prompt"?  Under Text -> Prompt for "Text" with message.

**Comment by MarkusBordihn** [comment]
@mrpoponz 
Thanks for the hint. This would be the same problem, but it could be solved on our end instead of the Blockly side.

Will handle all of these in #68.
