### ISSUE TITLE
[user feedback] Install failing with locale issue

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#65]
Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.
Reply
Application version: 3.5.30
Client version: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Reported date: 6/1/16 2:50 AM
Reported by: A Google User

**Comment by MarkusBordihn** [comment]
Chrome store related issue.
