### ISSUE TITLE
Share small programs by URL

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#73]
As reported by Branimir:

For sharing short programs it would be super cool if we could encode the entire program in a (potentially longish) URL. You press the "share" icon and you get back a URL that you can copy and paste into a chat window. Super nice for collaboration, online learning etc. 

We could even use goo.gl service (like Maps does) to shorten the URLs.

**Comment by MarkusBordihn** [comment]
Most browsers has an URL limitation of 4096 characters, but basically we already using such urls internally so we only need to make them visible over the UI. ;)
