### ISSUE TITLE
Implement XML + XSLT and C++

### ISSUE THREAD

**Issue by lolbinarycat** [google/coding-with-chrome#77]
I, for one, am not entirely satisfied with the selection of laguages that are availble currently.
like, what about c/c++?mabby xml?

**Comment by MarkusBordihn** [comment]
Possible candidate for C++ module:
https://github.com/felixhao28/JSCPP

@lolbinarycat 
Do you want the option to load, edit and store .xml files or is this more for an XML + XSLT integration?

**Comment by lolbinarycat** [comment]
more xml + xslt

**Comment by SetCodesToFire** [comment]
Hi, I want to help in this. Can you mention which folder I have to make the changes. Thanks a lot ⌨️

**Comment by tabshaikh** [comment]
@MarkusBordihn Hello how can i began contributing to this issue. Is there some mailing group that i could join. Thanks
