### ISSUE TITLE
Clicking on 'insert image' fails

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#80]
This works in a few modes that I try. Interface is broken

<img width="1300" alt="screen shot 2016-08-30 at 12 26 29 am" src="https://cloud.githubusercontent.com/assets/16690260/18070822/7b82c642-6e48-11e6-81a9-8c192a263095.png">

**Comment by MarkusBordihn** [comment]
5b81b911d609a5e8e13f375e75749a772db46573
