### ISSUE TITLE
connect an ev3 

### ISSUE THREAD

**Issue by jorgefuerte** [google/coding-with-chrome#87]

**Comment by jorgefuerte** [comment]
i would like to know do i connect my ev3 to coding with chorme

**Comment by MartenvanWezel** [comment]
You need to pair the EV3 with your computer - the instructions vary from device to device, but in general you need to make sure bluetooth is turned on, search for the EV3 from your computer, and then follow the instructions on the screen (both ev3 screen and computer screen).

When the pairing is succesful, CwC should auto-connect.
