### ISSUE TITLE
"if" block broken in Basic Coding

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#9]
<img width="314" alt="screen shot 2016-01-18 at 12 08 25 am" src="https://cloud.githubusercontent.com/assets/16690260/12380955/baaa90e8-bd77-11e5-91ac-c5bc65daa834.png">

**Comment by MarkusBordihn** [comment]
Its the Blockly default block, in which way is it broken ?

**Comment by MartenvanWezel** [comment]
I think instead of a black square it needed a 'cog' icon?
