### ISSUE TITLE
Create 'description/instruction box' for examples

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#90]
Perhaps this requires updating the CWC format, but essentially the key example is that the simple robotics EV3 Block grabber contains very little instructions on how to get this all set up.

Perhaps it's easy "use standard EV3 config xyz and make sure the wires abc are connected" but a tiny piece of text would be helpful. Happy to help write the text, but we need the tech.

**Comment by MarkusBordihn** [comment]
Any idea were this information should be visible and it which form ?

**Comment by MarkusBordihn** [comment]
The framework is implemented only the content is missing.
