### ISSUE TITLE
Save as new file doesn't alter the name of the window

### ISSUE THREAD

**Issue by MartenvanWezel** [google/coding-with-chrome#91]
Sorry if this is a repeat, it feels like we discussed this before.. but if I open an example, save as new file, the top title still says "EV3 Educator - Block Grabber".. this is counterintuitive, it should follow the saved filename IMO.

**Comment by MarkusBordihn** [comment]
For formats we could store the "title" we will use this information.
For raw formats like .js, .txt, .html were this is not possible we simple use the file name.

This will be closed as working as expected.
